export type Language = 'es' | 'en';

export const TRANSLATIONS = {
  es: {
    general: {
      cancel: 'Cancelar',
      save: 'Guardar',
      delete: 'Eliminar',
      confirm: 'Confirmar',
      loading: 'Cargando...',
      error: 'Error',
      success: '✓ Guardado correctamente',
      search: 'Buscar notas...',
      warning: 'Advertencia',
      attention: 'Atención',
    },
    sidebar: {
      allNotes: 'Todas las notas',
      floatingNotes: 'Sin carpeta',
      folders: 'Carpetas',
      newFolder: 'Nueva carpeta',
      folderName: 'Nombre de la carpeta',
      create: 'Crear',
      context: {
        edit: 'Editar carpeta',
        delete: 'Eliminar carpeta',
        deleteConfirm: '¿Eliminar la carpeta "{name}" y todas sus notas?',
      },
      recentTitle: 'Notas recientes',
      recentEdited: 'Editadas',
      recentOpened: 'Abiertas',
      recentCreated: 'Creadas',
      clearHistory: 'Limpiar historial',
    },
    noteList: {
      recent: 'Recientes',
      alphabetical: 'Alfabético',
      sortBy: 'Ordenar por',
      noNotes: 'Sin notas',
      noNotesDesc: 'Crea una nota para empezar a escribir.',
      unnamedNote: 'Nota sin título',
      deleteConfirm: '¿Eliminar esta nota?',
      editorActive: 'Nota activa en el editor',
    },
    editor: {
      placeholderTitle: 'Título de la nota...',
      placeholderBody: 'Empieza a escribir aquí...',
      saved: 'Guardado',
      saving: 'Guardando...',
      saveManual: 'Guardar',
      lineCounter: 'Lín {line}, Col {col}',
      capsLockActive: 'Bloq Mayús ACTIVO',
      capsLockAuto: '(Auto-desactivar: {status})',
      capsLockStatus: 'Desactivar Bloq Mayús por inactividad (Estado: {status})',
      capsLockToastActive: 'Bloq Mayús: ACTIVADO ⚠️',
      capsLockToastAuto: 'Bloq Mayús: AUTO-DESACTIVADO 💡',
      capsLockToastDisabled: 'Bloq Mayús: DESACTIVADO ✅',
      wordCount: '{words} palabras',
      charCount: '{chars} caracteres',
      readTime: '{time} min lectura',
      bold: 'Negrita',
      italic: 'Itálica',
      strike: 'Tachado',
      code: 'Código',
      heading1: 'Título 1',
      heading2: 'Título 2',
      bulletList: 'Lista viñetas',
      orderedList: 'Lista ordenada',
      codeBlock: 'Bloque de código',
      quote: 'Cita',
      horizontalRule: 'Línea horizontal',
      undo: 'Deshacer',
      redo: 'Rehacer',
      exportAs: 'Exportar como',
      exportPDF: 'Exportar PDF',
      exportHTML: 'Exportar HTML',
      exportMarkdown: 'Exportar Markdown',
    },
    settings: {
      title: '⚙️ Ajustes',
      tabs: {
        general: 'General',
        security: 'Seguridad',
        about: 'Acerca de',
      },
      visualTheme: 'Tema visual',
      active: '● Activo',
      activate: 'Click para activar',
      intensity: 'Intensidad de color',
      intensitySoft: 'Suave',
      intensityStrong: 'Intenso',
      intensityWarning: 'No aplica para Graphite o Light',
      customBg: 'Fondo Personalizado',
      changeImage: 'Cambiar imagen',
      glassEffect: 'Efecto Glass (Desenfoque)',
      opacityOverlay: 'Opacidad del Overlay',
      behavior: 'Comportamiento',
      closeToTray: 'Cerrar a la bandeja de sistema',
      closeToTrayDesc: 'Al presionar X, la app se mantendrá activa en la bandeja',
      startWithWindows: 'Iniciar con Windows (minimizado)',
      startWithWindowsDesc: 'La app se abrirá en la bandeja al arrancar el equipo',
      rememberLastNote: 'Recordar última nota al abrir',
      rememberLastNoteDesc: 'La app se reabrirá en la nota donde la dejaste',
      showLineCounter: 'Mostrar contador de líneas',
      showLineCounterDesc: 'Muestra la línea y columna actual en el editor',
      autosave: 'Autoguardado',
      autosaveDesc: 'Guardar automáticamente al editar. Si se desactiva, usa el botón Guardar en el editor.',
      capsLockUnlock: 'Desactivar Bloq Mayús por inactividad',
      capsLockUnlockDesc: 'Desactiva físicamente el Bloq Mayús tras un periodo ajustable de inactividad de teclado en el editor',
      inactivityTime: 'Tiempo de inactividad',
      capsLockSound: 'Sonido de Bloq Mayús',
      capsLockSoundDesc: 'Sonido al activarse o desactivarse físicamente el Bloq Mayús',
      soundPreview: 'Escuchar',
      soundPresets: {
        off: 'Silenciar (Sin sonido)',
        click: 'Click Mecánico ⌨️',
        beep: 'Chirp Cyber-Beep 🔊',
        chime: 'Chime Digital 🎵',
        glitch: 'Blip de Glitch ⚡',
      },
      soundScope: 'Ámbito del sonido',
      soundScopeDesc: 'Elige si el sonido suena solo en la app o globalmente',
      scopeApp: 'Solo dentro de la app 📱',
      scopeGlobal: 'Global en el sistema 🌍',
      languageSelect: 'Idioma de la interfaz',
      languageSelectDesc: 'Elige el idioma principal de CyberNotes',
      devTools: 'Abrir consola',
      dataFolder: 'Carpeta de datos',
      exportBackup: 'Exportar Backup (JSON)',
      importBackup: 'Importar Backup',
      toolsAndData: 'Herramientas y Datos',
    },
    maintenance: {
      title: 'Mantenimiento',
      checkUpdates: 'Buscar actualizaciones',
      checkUpdatesDesc: 'Busca e instala la última versión de CyberNotes',
      checkNow: 'Buscar ahora',
      checking: 'Buscando...',
      upToDate: '✓ CyberNotes está actualizado',
      updateAvailable: '¡Actualización disponible!',
      autoCheckUpdates: 'Buscar actualizaciones al iniciar',
      autoCheckUpdatesDesc: 'Revisa automáticamente si hay nuevas versiones al abrir la app',
    },
    security: {
      passwordDesc: 'La contraseña protege el acceso a la app. Deja los campos vacíos si no quieres contraseña.',
      placeholderCurrent: 'Contraseña actual (si tienes una)',
      placeholderNew: 'Nueva contraseña',
      placeholderConfirm: 'Confirmar nueva contraseña',
      savePassword: 'Guardar contraseña',
      removePassword: 'Quitar',
      removeConfirm: '¿Eliminar la contraseña de acceso? La app quedará sin protección.',
      lockAppNow: 'Bloquear app ahora',
      autoLockTitle: 'Auto-bloqueo por inactividad',
      autoLockDesc: 'La aplicación se bloqueará automáticamente si no detecta actividad del ratón o teclado durante el tiempo seleccionado.',
      autoLockOptions: {
        never: 'Nunca (Desactivado)',
        m1: 'Después de 1 minuto',
        m5: 'Después de 5 minutos',
        m15: 'Después de 15 minutos',
        m30: 'Después de 30 minutos',
        h1: 'Después de 1 hora',
        h2: 'Después de 2 horas',
        h4: 'Después de 4 horas',
        h8: 'Después de 8 horas',
        h12: 'Después de 12 horas',
        h24: 'Después de 24 horas',
      },
    },
    lockScreen: {
      enterPassword: 'Ingresa tu contraseña para continuar',
      noPassword: 'No has configurado una contraseña aún',
      placeholderPassword: 'Contraseña',
      verifying: 'Verificando...',
      unlock: 'Desbloquear',
      enter: 'Entrar',
      incorrectPassword: 'Contraseña incorrecta',
      verifyError: 'Error al verificar contraseña',
      minimize: 'Minimizar',
      maximize: 'Maximizar / Restaurar',
      close: 'Cerrar',
      showPassword: 'Mostrar contraseña',
      hidePassword: 'Ocultar contraseña',
    },
  },
  en: {
    general: {
      cancel: 'Cancel',
      save: 'Save',
      delete: 'Delete',
      confirm: 'Confirm',
      loading: 'Loading...',
      error: 'Error',
      success: '✓ Saved successfully',
      search: 'Search notes...',
      warning: 'Warning',
      attention: 'Attention',
    },
    sidebar: {
      allNotes: 'All Notes',
      floatingNotes: 'Unfiled',
      folders: 'Folders',
      newFolder: 'New Folder',
      folderName: 'Folder Name',
      create: 'Create',
      context: {
        edit: 'Edit folder',
        delete: 'Delete folder',
        deleteConfirm: 'Delete folder "{name}" and all its notes?',
      },
      recentTitle: 'Recent Notes',
      recentEdited: 'Edited',
      recentOpened: 'Opened',
      recentCreated: 'Created',
      clearHistory: 'Clear history',
    },
    noteList: {
      recent: 'Recent',
      alphabetical: 'Alphabetical',
      sortBy: 'Sort by',
      noNotes: 'No Notes',
      noNotesDesc: 'Create a note to start writing.',
      unnamedNote: 'Unnamed Note',
      deleteConfirm: 'Delete this note?',
      editorActive: 'Active in editor',
    },
    editor: {
      placeholderTitle: 'Note Title...',
      placeholderBody: 'Start typing here...',
      saved: 'Saved',
      saving: 'Saving...',
      saveManual: 'Save',
      lineCounter: 'Ln {line}, Col {col}',
      capsLockActive: 'Caps Lock ACTIVE',
      capsLockAuto: '(Auto-disable: {status})',
      capsLockStatus: 'Disable Caps Lock on inactivity (Status: {status})',
      capsLockToastActive: 'Caps Lock: ACTIVATED ⚠️',
      capsLockToastAuto: 'Caps Lock: AUTO-DISABLED 💡',
      capsLockToastDisabled: 'Caps Lock: DISABLED ✅',
      wordCount: '{words} words',
      charCount: '{chars} characters',
      readTime: '{time} min read',
      bold: 'Bold',
      italic: 'Italic',
      strike: 'Strikethrough',
      code: 'Code',
      heading1: 'Heading 1',
      heading2: 'Heading 2',
      bulletList: 'Bullet List',
      orderedList: 'Ordered List',
      codeBlock: 'Code Block',
      quote: 'Quote',
      horizontalRule: 'Horizontal Rule',
      undo: 'Undo',
      redo: 'Redo',
      exportAs: 'Export as',
      exportPDF: 'Export PDF',
      exportHTML: 'Export HTML',
      exportMarkdown: 'Export Markdown',
    },
    settings: {
      title: '⚙️ Settings',
      tabs: {
        general: 'General',
        security: 'Security',
        about: 'About',
      },
      visualTheme: 'Visual Theme',
      active: '● Active',
      activate: 'Click to activate',
      intensity: 'Color Intensity',
      intensitySoft: 'Soft',
      intensityStrong: 'Strong',
      intensityWarning: 'Does not apply to Graphite or Light',
      customBg: 'Custom Background',
      changeImage: 'Change Image',
      glassEffect: 'Glass Effect (Blur)',
      opacityOverlay: 'Overlay Opacity',
      behavior: 'Behavior',
      closeToTray: 'Close to System Tray',
      closeToTrayDesc: 'When pressing X, the app remains running in the tray',
      startWithWindows: 'Start with Windows (minimized)',
      startWithWindowsDesc: 'The app will open in the tray when the system starts',
      rememberLastNote: 'Remember last note on open',
      rememberLastNoteDesc: 'The app will reopen at the note where you left off',
      showLineCounter: 'Show Line Counter',
      showLineCounterDesc: 'Shows the current line and column in the editor',
      autosave: 'Autosave',
      autosaveDesc: 'Automatically save when editing. If disabled, use the Save button in the editor.',
      capsLockUnlock: 'Disable Caps Lock on inactivity',
      capsLockUnlockDesc: 'Physically deactivates Caps Lock after an adjustable period of keyboard inactivity in the editor',
      inactivityTime: 'Inactivity Time',
      capsLockSound: 'Caps Lock Sound',
      capsLockSoundDesc: 'Sound played when Caps Lock is physically turned on or off',
      soundPreview: 'Preview',
      soundPresets: {
        off: 'Muted (No sound)',
        click: 'Mechanical Click ⌨️',
        beep: 'Cyber-Beep Chirp 🔊',
        chime: 'Digital Chime 🎵',
        glitch: 'Glitch Blip ⚡',
      },
      soundScope: 'Sound Scope',
      soundScopeDesc: 'Choose if the sound plays only inside the app or globally',
      scopeApp: 'Only inside the app 📱',
      scopeGlobal: 'Global in the system 🌍',
      languageSelect: 'Interface Language',
      languageSelectDesc: 'Choose the main language for CyberNotes',
      devTools: 'Open Console',
      dataFolder: 'Data Folder',
      exportBackup: 'Export Backup (JSON)',
      importBackup: 'Import Backup',
      toolsAndData: 'Tools & Data',
    },
    maintenance: {
      title: 'Maintenance',
      checkUpdates: 'Check for updates',
      checkUpdatesDesc: 'Search and install the latest version of CyberNotes',
      checkNow: 'Check now',
      checking: 'Checking...',
      upToDate: '✓ CyberNotes is up to date',
      updateAvailable: 'Update available!',
      autoCheckUpdates: 'Auto-check for updates on startup',
      autoCheckUpdatesDesc: 'Automatically checks for new versions when the app starts',
    },
    security: {
      passwordDesc: 'The password protects access to the app. Leave fields empty if you don\'t want a password.',
      placeholderCurrent: 'Current password (if you have one)',
      placeholderNew: 'New password',
      placeholderConfirm: 'Confirm new password',
      savePassword: 'Save password',
      removePassword: 'Remove',
      removeConfirm: 'Remove access password? The app will have no protection.',
      lockAppNow: 'Lock app now',
      autoLockTitle: 'Auto-lock on inactivity',
      autoLockDesc: 'The application will lock automatically if no mouse or keyboard activity is detected for the selected duration.',
      autoLockOptions: {
        never: 'Never (Disabled)',
        m1: 'After 1 minute',
        m5: 'After 5 minutes',
        m15: 'After 15 minutes',
        m30: 'After 30 minutes',
        h1: 'After 1 hour',
        h2: 'After 2 hours',
        h4: 'After 4 hours',
        h8: 'After 8 hours',
        h12: 'After 12 hours',
        h24: 'After 24 hours',
      },
    },
    lockScreen: {
      enterPassword: 'Enter your password to continue',
      noPassword: 'You have not set a password yet',
      placeholderPassword: 'Password',
      verifying: 'Verifying...',
      unlock: 'Unlock',
      enter: 'Enter',
      incorrectPassword: 'Incorrect password',
      verifyError: 'Error verifying password',
      minimize: 'Minimize',
      maximize: 'Maximize / Restore',
      close: 'Close',
      showPassword: 'Show password',
      hidePassword: 'Hide password',
    },
  },
};
